name: Smell The Rage
favicon: null
layout_spectrum: 0.99819
typography_spectrum: 0.22764312662184238
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6b69f'
    - '#31271d'
    - '#675b4b'
    - '#020200'
    - '#999276'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
